### ISSUE TITLE
Bad PECL archive

### ISSUE THREAD

**Issue by remicollet** [microsoft/mysqlnd_azure#3]
$ tar tf mysqlnd_azure-1.0.0.tgz 
```
mysqlnd_azure/
mysqlnd_azure/.git/
mysqlnd_azure/.gitignore
mysqlnd_azure/.git/branches/
mysqlnd_azure/.git/config
mysqlnd_azure/.git/description
mysqlnd_azure/.git/FETCH_HEAD
mysqlnd_azure/.git/HEAD
... 
mysqlnd_azure/redirect_cache.c
mysqlnd_azure/tests/
mysqlnd_azure/tests/connect.inc
mysqlnd_azure/tests/mysqli_azure_redirection_disabled.phpt
mysqlnd_azure/tests/mysqli_azure_redirection_enabled.phpt
mysqlnd_azure/tests/skipif.inc
mysqlnd_azure/tests/skipifconnectfailure.inc
package.xml

```

* Top directory shoud be `mysqlnd_azure-1.0.0`
* .git directory is obviously not needed
* in git, package.xml don't need to have md5sum (genereated during the release)

So please use `pecl package `command to generate the archive.

Additional tips:  use normalized `PHP_MYSQLND_AZURE_VERSION` macro instead of `EXT_MYSQLND_AZURE_VERSION`, so its value will be checked during upload on pecl forge.

**Comment by GuuBu** [comment]
Hi  Remi,
Thanks a lot. Yes, the package of version 1.0.0 is manually created one,  and it does not work because of the wrong folder name inside. I've documented it in README.md, but cannot  remove the package from PECL website. May I ask is there a way to remove the package, is it a better way to do so? If it is possible, I'll remove the package and update document.

Thanks & Best Regards,
Qianqian Bu

**Comment by remicollet** [comment]
I don't think  there is any value in removing the broken archive

BTW, this is still possible, using the "pen"  icon (near "edit maintainers") on https://pecl.php.net/package/mysqlnd_azure

**Comment by GuuBu** [comment]
That's a lot, I find the approach. But I think we can keep it as it is. 

Best Regards,
Qianqian Bu
